CE_ItemDataConfig {
 m_ItemData {
  CE_ItemData "{68D75804149D45DF}" {
   m_sName "TestVehicle"
   m_sPrefab "{54C3CC22DEBD57BE}Prefabs/Vehicles/Wheeled/S105/S105_beige.et"
   m_iLifetime 30
   m_iRestock 30
   m_iQuantityMaximum 90
   m_iQuantityMinimum 20
   m_ItemCategory VEHICLES
   m_ItemUsages 255
   m_ItemTiers 15
  }
 }
}