StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{68A230DBDC2F4D74}" {
   Id "CE-Item_Bookshelf_Description"
   Target_en_us "A book shelf that may contain various items."
   Target_fr_fr "Une étagère pouvant contenir divers objets."
   Target_it_it "Una libreria che può contenere vari oggetti."
   Target_de_de "Ein Bücherregal, das verschiedene Gegenstände enthalten kann."
   Target_es_es "Una estantería que puede contener diversos objetos."
   Target_cs_cz "Knihovna, která může obsahovat různé předměty."
   Target_pl_pl "Półka na książki, na której można przechowywać różne przedmioty."
   Target_ru_ru "Книжная полка, на которой могут находиться различные предметы."
   Target_ja_jp "様々なアイテムを収納できる本棚。"
   Target_ko_kr "다양한 물건을 담을 수 있는 책장."
   Target_pt_br "Uma estante que pode conter vários itens."
   Target_zh_cn "一个可能存放各种物品的书架。"
   Target_uk_ua "Книжкова полиця, на якій можуть зберігатися різні предмети."
   Status DEVELOPMENT_DONE
   Modified 1755466704
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{65AF0EA1BA57549A}" {
   Id "CE-Item_Bookshelf_Name"
   Target_en_us "Bookshelf"
   Target_fr_fr "Bibliothèque"
   Target_it_it "Scaffale"
   Target_de_de "Bücherregal"
   Target_es_es "Estantería"
   Target_cs_cz "Regál s knihami"
   Target_pl_pl "Półka na książki"
   Target_ru_ru "Книжная полка"
   Target_ja_jp "本棚"
   Target_ko_kr "책장"
   Target_pt_br "Estante de livros"
   Target_zh_cn "书架"
   Target_uk_ua "Книжкова полиця"
   Status DEVELOPMENT_DONE
   Modified 1705973058
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{68A230DACDA384BB}" {
   Id "CE-Item_Cabinet_Description"
   Target_en_us "A cabinet that may contain various items."
   Target_fr_fr "Une armoire pouvant contenir divers objets."
   Target_it_it "Un armadio che può contenere vari oggetti."
   Target_de_de "Ein Schrank, der verschiedene Gegenstände enthalten kann."
   Target_es_es "Un armario que puede contener diversos objetos."
   Target_cs_cz "Skříňka, která může obsahovat různé předměty."
   Target_pl_pl "Szafka, w której można przechowywać różne przedmioty."
   Target_ru_ru "Шкаф, в котором могут храниться различные предметы."
   Target_ja_jp "様々な物品を収納できるキャビネット。"
   Target_ko_kr "다양한 물건을 담을 수 있는 캐비닛."
   Target_pt_br "Um armário que pode conter vários itens."
   Target_zh_cn "一个可能存放各种物品的柜子。"
   Target_uk_ua "Шафа, в якій можуть зберігатися різні предмети."
   Status DEVELOPMENT_DONE
   Modified 1755467098
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{65B13D6BA4D63CBA}" {
   Id "CE-Item_Cabinet_Name"
   Target_en_us "Cabinet"
   Target_it_it "Armadietto"
   Target_de_de "Kabinett"
   Target_es_es "Armario"
   Target_cs_cz "Kabinet"
   Target_pl_pl "Szafka"
   Target_ru_ru "Кабинет"
   Target_ja_jp "キャビネット"
   Target_ko_kr "캐비닛"
   Target_pt_br "Gabinete"
   Target_zh_cn "内阁"
   Target_uk_ua "Кабінет"
   Status DEVELOPMENT_DONE
   Modified 1706117512
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{68A230DA5C03379B}" {
   Id "CE-Item_Chest_Description"
   Target_en_us "A chest that may contain various items."
   Target_fr_fr "Un coffre pouvant contenir divers objets."
   Target_it_it "Uno scrigno che può contenere vari oggetti."
   Target_de_de "Eine Truhe, die verschiedene Gegenstände enthalten kann."
   Target_es_es "Un cofre que puede contener varios objetos."
   Target_cs_cz "Truhla, která může obsahovat různé předměty."
   Target_pl_pl "Skrzynia, która może zawierać różne przedmioty."
   Target_ru_ru "Сундук, в котором могут находиться различные предметы."
   Target_ja_jp "様々なアイテムが入っているかもしれない箱。"
   Target_ko_kr "다양한 아이템이 들어 있을 수 있는 상자."
   Target_pt_br "Um baú que pode conter vários itens."
   Target_zh_cn "一个可能装有各种物品的箱子。"
   Target_uk_ua "Скриня, яка може містити різні предмети."
   Status DEVELOPMENT_DONE
   Modified 1755467393
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{65B13D6813C33E5B}" {
   Id "CE-Item_Chest_Name"
   Target_en_us "Chest"
   Target_fr_fr "Coffre"
   Target_it_it "Petto"
   Target_de_de "Brustkorb"
   Target_es_es "Pecho"
   Target_cs_cz "Hrudník"
   Target_pl_pl "Kufer"
   Target_ru_ru "Грудь"
   Target_ja_jp "胸部"
   Target_ko_kr "가슴"
   Target_pt_br "Caixa"
   Target_zh_cn "胸部"
   Target_uk_ua "Груди"
   Status DEVELOPMENT_DONE
   Modified 1706117697
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{68A230DB7B369252}" {
   Id "CE-Item_Cupboard_Description"
   Target_en_us "A cupboard that may contain various items."
   Target_fr_fr "Une armoire pouvant contenir divers objets."
   Target_it_it "Un armadio che può contenere vari oggetti."
   Target_de_de "Ein Schrank, der verschiedene Gegenstände enthalten kann."
   Target_es_es "Un armario que puede contener diversos artículos."
   Target_cs_cz "Skříň, která může obsahovat různé předměty."
   Target_pl_pl "Szafka, w której mogą znajdować się różne przedmioty."
   Target_ru_ru "Шкаф, в котором могут храниться различные предметы."
   Target_ja_jp "様々な物品が入っているかもしれない戸棚。"
   Target_ko_kr "여러 가지 물건이 들어 있을 수 있는 찬장."
   Target_pt_br "Um armário que pode conter vários itens."
   Target_zh_cn "一个可能存放各种物品的橱柜。"
   Target_uk_ua "Шафа, в якій можуть зберігатися різні предмети."
   Status DEVELOPMENT_DONE
   Modified 1755466965
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{65AF0EA0679DE5FB}" {
   Id "CE-Item_Cupboard_Name"
   Target_en_us "Cupboard"
   Target_fr_fr "Armoire"
   Target_it_it "Armadio"
   Target_de_de "Schrank"
   Target_es_es "Armario"
   Target_cs_cz "Skříň"
   Target_pl_pl "Szafka"
   Target_ru_ru "Шкаф"
   Target_ja_jp "食器棚"
   Target_ko_kr "찬장"
   Target_pt_br "Armário"
   Target_zh_cn "橱柜"
   Target_uk_ua "Шафа"
   Status DEVELOPMENT_DONE
   Modified 1705973171
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{68A230C5FF987D55}" {
   Id "CE-Item_Desk_Description"
   Target_en_us "A desk that may contain various items."
   Target_fr_fr "Un bureau pouvant contenir divers objets."
   Target_it_it "Una scrivania che può contenere vari oggetti."
   Target_de_de "Ein Schreibtisch, der verschiedene Gegenstände enthalten kann."
   Target_es_es "Un escritorio que puede contener varios objetos."
   Target_cs_cz "Stůl, na kterém mohou být různé předměty."
   Target_pl_pl "Biurko, na którym mogą znajdować się różne przedmioty."
   Target_ru_ru "Стол, на котором могут находиться различные предметы."
   Target_ja_jp "様々な物品が入っている可能性のある机。"
   Target_ko_kr "다양한 물건이 들어 있을 수 있는 책상."
   Target_pt_br "Uma mesa que pode conter vários itens."
   Target_zh_cn "一张可能存放各种物品的桌子。"
   Target_uk_ua "Стіл, на якому можуть знаходитися різні предмети."
   Status DEVELOPMENT_DONE
   Modified 1755467802
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{65B32156B55B1550}" {
   Id "CE-Item_Desk_Name"
   Target_en_us "Desk"
   Target_fr_fr "Bureau"
   Target_it_it "Scrivania"
   Target_de_de "Schreibtisch"
   Target_es_es "Escritorio"
   Target_cs_cz "Psací stůl"
   Target_pl_pl "Biurko"
   Target_ru_ru "Стол"
   Target_ja_jp "デスク"
   Target_ko_kr "데스크"
   Target_pt_br "Mesa"
   Target_zh_cn "办公桌"
   Target_uk_ua "Стіл"
   Status DEVELOPMENT_DONE
   Modified 1706238806
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{68A230C564C04085}" {
   Id "CE-Item_Dresser_Description"
   Target_en_us "A dresser that may contain various items."
   Target_fr_fr "Une commode pouvant contenir divers articles."
   Target_it_it "Un comò che può contenere vari oggetti."
   Target_de_de "Eine Kommode, die verschiedene Gegenstände enthalten kann."
   Target_es_es "Una cómoda que puede contener diversos artículos."
   Target_cs_cz "Komoda, která může obsahovat různé předměty."
   Target_pl_pl "Komoda, w której można przechowywać różne przedmioty."
   Target_ru_ru "Комод, в котором могут храниться различные предметы."
   Target_ja_jp "様々な物品を収納できるドレッサー。"
   Target_ko_kr "다양한 물건을 담을 수 있는 옷장."
   Target_pt_br "Uma cômoda que pode conter vários itens."
   Target_zh_cn "一个可能存放各种物品的梳妆台。"
   Target_uk_ua "Комод, в якому можуть зберігатися різні предмети."
   Status DEVELOPMENT_DONE
   Modified 1755467972
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{65B321503CACD83A}" {
   Id "CE-Item_Dresser_Name"
   Target_en_us "Dresser"
   Target_fr_fr "Commode"
   Target_it_it "Comò"
   Target_de_de "Kommode"
   Target_es_es "Cómoda"
   Target_cs_cz "Komoda"
   Target_pl_pl "Komoda"
   Target_ru_ru "Комод"
   Target_ja_jp "ドレッサー"
   Target_ko_kr "드레서"
   Target_pt_br "Cômoda"
   Target_zh_cn "梳妆台"
   Target_uk_ua "Комод"
   Status DEVELOPMENT_DONE
   Modified 1706241371
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{65B3215C83CC64CC}" {
   Id "CE-Item_FirstAid_Name"
   Target_en_us "First Aid"
   Target_fr_fr "Premiers secours"
   Target_it_it "Primo soccorso"
   Target_de_de "Erste Hilfe"
   Target_es_es "Primeros auxilios"
   Target_cs_cz "První pomoc"
   Target_pl_pl "Pierwsza pomoc"
   Target_ru_ru "Первая помощь"
   Target_ja_jp "応急処置"
   Target_ko_kr "응급 처치"
   Target_pt_br "Primeiros socorros"
   Target_zh_cn "急救"
   Target_uk_ua "Перша допомога"
   Status DEVELOPMENT_DONE
   Modified 1706243586
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{68A230C53F8CF00B}" {
   Id "CE-Item_Generic_Description"
   Target_en_us "May contain various items."
   Target_fr_fr "Peut contenir divers articles."
   Target_it_it "Può contenere vari articoli."
   Target_de_de "Kann verschiedene Artikel enthalten."
   Target_es_es "Puede contener varios artículos."
   Target_cs_cz "Může obsahovat různé položky."
   Target_pl_pl "Może zawierać różne przedmioty."
   Target_ru_ru "Может содержать различные предметы."
   Target_ja_jp "様々なアイテムが含まれている場合があります。"
   Target_ko_kr "다양한 품목이 포함될 수 있습니다."
   Target_pt_br "Pode conter vários itens."
   Target_zh_cn "可能包含各种物品。"
   Target_uk_ua "Може містити різні предмети."
   Status DEVELOPMENT_DONE
   Modified 1755468982
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{65B559EFDA88DD00}" {
   Id "CE-Item_Nightstand_Name"
   Target_en_us "Nightstand"
   Target_fr_fr "Table de nuit"
   Target_it_it "Comodino"
   Target_de_de "Nachttisch"
   Target_es_es "Mesilla de noche"
   Target_cs_cz "Noční stolek"
   Target_pl_pl "Szafka nocna"
   Target_ru_ru "Тумбочка"
   Target_ja_jp "ナイトスタンド"
   Target_ko_kr "나이트 스탠드"
   Target_pt_br "Mesa de cabeceira"
   Target_zh_cn "床头柜"
   Target_uk_ua "Тумбочка"
   Modified 1706385861
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{65B559E9D5C1CE63}" {
   Id "CE-Item_Pantry_Name"
   Target_en_us "Pantry"
   Target_fr_fr "Garde-manger"
   Target_it_it "Dispensa"
   Target_de_de "Speisekammer"
   Target_es_es "Despensa"
   Target_cs_cz "Spíž"
   Target_pl_pl "Spiżarnia"
   Target_ru_ru "Кладовая"
   Target_ja_jp "パントリー"
   Target_ko_kr "식료품 저장실"
   Target_pt_br "Despensa"
   Target_zh_cn "储藏室"
   Target_uk_ua "Комора"
   Status DEVELOPMENT_DONE
   Modified 1706386773
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{65B559E4B796F466}" {
   Id "CE-Item_Toolbox_Name"
   Target_en_us "Toolbox"
   Target_fr_fr "Boîte à outils"
   Target_it_it "Cassetta degli attrezzi"
   Target_de_de "Werkzeugkasten"
   Target_es_es "Caja de herramientas"
   Target_pl_pl "Zestaw narzędzi"
   Target_ru_ru "Ящик для инструментов"
   Target_ja_jp "ツールボックス"
   Target_ko_kr "도구 상자"
   Target_pt_br "Caixa de ferramentas"
   Target_zh_cn "工具箱"
   Target_uk_ua "Інструментарій"
   Status DEVELOPMENT_DONE
   Modified 1706388279
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{68A230D842DA5006}" {
   Id "CE-Item_Wardrobe_Description"
   Target_en_us "A wardrobe that may contain various items."
   Target_fr_fr "Une armoire pouvant contenir divers articles."
   Target_it_it "Un armadio che può contenere vari oggetti."
   Target_de_de "Ein Kleiderschrank, der verschiedene Gegenstände enthalten kann."
   Target_es_es "Un armario que puede contener diversos artículos."
   Target_cs_cz "Šatník, který může obsahovat různé předměty."
   Target_pl_pl "Szafa, która może zawierać różne przedmioty."
   Target_ru_ru "Шкаф для одежды, в котором могут храниться различные предметы."
   Target_ja_jp "様々なアイテムが入っているかもしれないワードローブ。"
   Target_ko_kr "다양한 물건이 들어 있을 수 있는 옷장."
   Target_pt_br "Um guarda-roupa que pode conter vários itens."
   Target_zh_cn "一个可能包含各种物品的衣柜。"
   Target_uk_ua "Шафа, яка може містити різні предмети."
   Status DEVELOPMENT_DONE
   Modified 1755467228
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{65B559EA2F1297B9}" {
   Id "CE-Item_Wardrobe_Name"
   Target_en_us "Wardrobe"
   Target_fr_fr "Penderie"
   Target_it_it "Armadio"
   Target_de_de "Garderobe"
   Target_es_es "Armario"
   Target_cs_cz "Šatní skříň"
   Target_pl_pl "Szafa"
   Target_ru_ru "Шкаф"
   Target_ja_jp "ワードローブ"
   Target_ko_kr "옷장"
   Target_pt_br "Guarda-roupa"
   Target_zh_cn "衣柜"
   Target_uk_ua "Гардероб"
   Status DEVELOPMENT_DONE
   Modified 1706387177
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{65B559E6D20ECCBB}" {
   Id "CE-Item_Workbench_Name"
   Target_en_us "Workbench"
   Target_fr_fr "Établi"
   Target_it_it "Banco di lavoro"
   Target_de_de "Werkbank"
   Target_es_es "Banco de trabajo"
   Target_cs_cz "Pracovní stůl"
   Target_pl_pl "Stół warsztatowy"
   Target_ru_ru "Верстак"
   Target_ja_jp "ワークベンチ"
   Target_ko_kr "워크벤치"
   Target_pt_br "Bancada de trabalho"
   Target_zh_cn "工作台"
   Target_uk_ua "Верстак"
   Status DEVELOPMENT_DONE
   Modified 1706389003
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{65B3215E30E6724A}" {
   Id "CE-UserAction_Search"
   Target_en_us "Search"
   Target_fr_fr "Recherche"
   Target_it_it "Ricerca"
   Target_de_de "Suche"
   Target_es_es "Buscar en"
   Target_cs_cz "Vyhledávání"
   Target_pl_pl "Wyszukiwanie"
   Target_ru_ru "Поиск"
   Target_ja_jp "検索"
   Target_ko_kr "검색"
   Target_pt_br "Pesquisa"
   Target_zh_cn "搜索"
   Target_uk_ua "Пошук"
   Status DEVELOPMENT_DONE
   Modified 1706242481
   Author "Cashew"
   LastChanged "Cashew"
  }
  CustomStringTableItem "{65AF0EA17A002BA6}" {
   Id "CE-UserAction_SearchContainer"
   Target_en_us "Search Container"
   Target_fr_fr "Conteneur de recherche"
   Target_it_it "Contenitore di ricerca"
   Target_de_de "Suche Container"
   Target_es_es "Contenedor de búsqueda"
   Target_cs_cz "Vyhledávací kontejner"
   Target_pl_pl "Pojemnik wyszukiwania"
   Target_ru_ru "Контейнер для поиска"
   Target_ja_jp "検索コンテナ"
   Target_ko_kr "컨테이너 검색"
   Target_pt_br "Contêiner de pesquisa"
   Target_zh_cn "搜索集装箱"
   Target_uk_ua "Контейнер пошуку"
   Status DEVELOPMENT_DONE
   Modified 1705972755
   Author "Cashew"
   LastChanged "Cashew"
  }
 }
}